# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class New < Formula
  desc "cookiecutter wrapper, let you search through github for template"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mJehanno/new/releases/download/v0.1.0/new_0.1.0_Darwin_arm64.tar.gz"
      sha256 "804a2b0b9b0328ec546788c769e908fb31a2241518bdcbe6937d5075d036e9e7"

      def install
        bin.install "new"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mJehanno/new/releases/download/v0.1.0/new_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "918068d8d711e5dffb7ab67586bcb2a51820456c047d3d316553bc011b8b4ef4"

      def install
        bin.install "new"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mJehanno/new/releases/download/v0.1.0/new_0.1.0_Linux_arm64.tar.gz"
      sha256 "7ec35058f7421f07bdbbfaba702712b2d490094d1ab22c1376d9569a09ceff5f"

      def install
        bin.install "new"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mJehanno/new/releases/download/v0.1.0/new_0.1.0_Linux_x86_64.tar.gz"
      sha256 "c9a2302db405c87c31ebf13812bd6212189c930ca28773893f00b9ee57666b88"

      def install
        bin.install "new"
      end
    end
  end

  depends_on "cookiecutter"
end
