# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class New < Formula
  desc "cookiecutter wrapper, let you search through github for template"
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mJehanno/new/releases/download/v0.1.2/new_0.1.2_Darwin_arm64.tar.gz"
      sha256 "d2596421e3617a3e04777f69a91718b150602a07cd266cf19e5377c451805341"

      def install
        bin.install "new"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mJehanno/new/releases/download/v0.1.2/new_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "267ae44dc6bda88f75da37489f10b30e434a6afea75ab8473167ec8de371ab69"

      def install
        bin.install "new"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mJehanno/new/releases/download/v0.1.2/new_0.1.2_Linux_arm64.tar.gz"
      sha256 "9a1924af12e268168785d29bc3b758696dc59757839b28c68a32048151a4c898"

      def install
        bin.install "new"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mJehanno/new/releases/download/v0.1.2/new_0.1.2_Linux_x86_64.tar.gz"
      sha256 "021186d0dd9612db11a76bb5b94cd5b453b4429a0af71dac4768305672f6a8e8"

      def install
        bin.install "new"
      end
    end
  end

  depends_on "cookiecutter"
end
